name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
       
jobs:
  build_and_push_backend:
    name: Build and push backend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to DockerHub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      
    - name: Build and push backend
      working-directory: backend
      run: |
        docker build -t jakubpawlicki/eb-zad-backend .
        docker push jakubpawlicki/eb-zad-backend
        
  send_email:
    name: Send e-mail notification
    needs: build_and_push_backend
    runs-on: ubuntu-latest
    steps:
    - name: Send email notification
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: eb.zad.10@gmail.com
        password: ${{ secrets.GMAIL_PASSWORD }}
        subject: Budowanie zakończone
        body: Backend aplikacji został pomyślnie zbudowany i pushowany.
        to: jakub.pawlicki@student.uj.edu.pl
        from: eb.zad.10@gmail.com

  deploy_backend:
    needs: build_and_push_backend
    runs-on: ubuntu-latest
    name: Deploy backend
    steps:
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'eb-zad10-backend'
        images: 'jakubpawlicki/eb-zad-backend:latest'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

        
  build_and_deploy_job_frontend:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and deploy frontend
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_MOSS_09004DA03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./frontend" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######


  run_selenium_tests:
    name: Selenium tests
    needs: 
    - deploy_backend
    - build_and_deploy_job_frontend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Google Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
    
    - name: Run tests
      run: |
        pytest tests/

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_MOSS_09004DA03 }}
          action: "close"
